<?php

define('BASE_URL', variable_get('contextual_baseurl', 'http://ows9.csiss.gmu.edu:9008/acpweb/'));
define('FEEDS_URL', variable_get('contextual_feedsurl', 'GetFeedsView'));
define('PAPERS_URL', variable_get('contextual_papersurl', 'GetPapersView'));
define('REQUEST_URL', variable_get('contextual_requesturl', 'http://54.191.97.139/sites/all/modules/contextual_metadata/request.php'));

/**
 * Implements hook_ctools_plugin_directory().
 */
function contextual_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/'.$plugin_type;
  }
}

/**
 * Admin configuration menu
 */
function contextual_admin() {
  $form = array();
  $form['contextual_baseurl'] = array(
    '#type' => 'textfield',
    '#title' => t('GMU Base URL'),
    '#default_value' => variable_get('contextual_baseurl', 'http://ows9.csiss.gmu.edu:9008/acpweb/'),
    '#description' => t("The base url for all metadata requests. Please include trailing slash."),
    '#required' => TRUE,
  );
  $form['contextual_feedsurl'] = array(
  	'#type' => 'textfield',
  	'#title' => t('FeedsView endpoint url'),
  	'#default_value' => variable_get('contextual_feedsurl', 'GetFeedsView'),
  	'#description' => t('The chunk for FeedsView requests.'),
  	'#required' => TRUE,
  );
  $form['contextual_papersurl'] = array(
  	'#type' => 'textfield',
  	'#title' => t('PapersView endpoint url'),
  	'#default_value' => variable_get('contextual_papersurl', 'GetPapersView'),
  	'#description' => t('The chunk for PapersView requests.'),
  	'#required' => TRUE,
  );
  return system_settings_form($form);
}

function contextual_menu() {
  $items = array();
  $items['admin/settings/contextual'] = array(
    'title' => 'Contextual metadata module settings',
    'description' => 'Settings for the contextual metadata module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('contextual_admin'),
    'access arguments' => array('administer Contextual Metadata settings'),
    'type' => MENU_NORMAL_ITEM,
   );
  return $items;
}

function contextual_theme() {
  	return array(
    	'sensor_tags' => array(
     	 	'render element' => 'data',
      		'template' => 'sensor_tags',
      		'path' => drupal_get_path('module', 'contextual') . '/templates',
      		'theme path' => drupal_get_path('module', 'contextual') . '/templates',
    	),
    	'param_tags' => array(
    		'render element' => 'data',
    		'template' => 'param_tags',
    		'path' => drupal_get_path('module', 'contextual') . '/templates',
    		'theme path' => drupal_get_path('module', 'contextual') . '/templates'
    	),
    	'app_tags' => array(
    		'render element' => 'data',
    		'template' => 'app_tags',
    		'path' => drupal_get_path('module', 'contextual') . '/templates',
    		'theme path' => drupal_get_path('module', 'contextual') . '/templates'
    	),
    	'feeds' => array(
    		'render element' => 'data',
    		'template' => 'feeds',
    		'path' => drupal_get_path('module', 'contextual') . '/templates',
    		'theme path' => drupal_get_path('module', 'contextual') . '/templates'
    	),
    	'papers' => array(
    		'render element' => 'data',
    		'template' => 'papers',
    		'path' => drupal_get_path('module', 'contextual') . '/templates',
    		'theme path' => drupal_get_path('module', 'contextual') . '/templates'
    	),
    	'options' => array(
    		'render element' => 'data',
    		'template' => 'options',
    		'path' => drupal_get_path('module', 'contextual') . '/templates',
    		'theme path' => drupal_get_path('module', 'contextual') . '/templates'
    	),
  	);
}